### ISSUE TITLE
开启代理/启动游戏 后点 设置/关于 切回去按钮会变回开启代理

### ISSUE THREAD

**Issue by tangtangebusi** [gc-toolkit/Launcher#3]
开启代理/启动游戏 后点 设置/关于 切回去按钮会变回开启代理

https://user-images.githubusercontent.com/67052443/206088392-67c47890-1d28-41a4-81bd-3f421ec57203.mp4

**Comment by SwetyCore** [comment]
太神秘的bug，我木有办法
