### ISSUE TITLE
无法找到grasscutter服务器

### ISSUE THREAD

**Issue by EnderMan8888** [gc-toolkit/Launcher#8]

**Comment by SwetyCore** [comment]
请详细描述你的问题

**Comment by CreatorCSIE** [comment]
![image](https://user-images.githubusercontent.com/68942543/208223774-45edcad0-2b97-4e55-85d7-2f48dd695a87.png)

**Comment by SwetyCore** [comment]
右键手动进行添加
启动器不提供可用服务器
